### ISSUE TITLE
[feature request] skip git check on untracked files

### ISSUE THREAD

**Issue by Tux** [briandfoy/module-release#47]
If working on a project where new tests are work in progress, and these tests are not (yet) in git nor in the MANIFEST, I do *not* see this as e reason for `release -t` to fail. So untracked files IMHO should not cause a FAIL.

```
=item Check that source control is up-to-date

If there are modified files, added files, or extra files so that
source control complains, fail.
```
I'd like to see an option (which I would default to be enabled in my `.releaserc` files), to make that
```
=item Check that source control is up-to-date

If there are modified files so that source control complains, fail.
```
I've done that by adding `-uno`:
```
sub check_vcs {
	my $self = shift;

	$self->_print( "Checking state of Git... " );

	my $git_status = $self->run('git status -s -uno 2>&1');
```
But if you think this could help others too, it should be an option

**Comment by briandfoy** [comment]
I think there's a way to get what you want, but I'm wondering what the best global solution would be. 

Your case is the reason I made `release` fail. That's almost it's entire job. I don't wait to track and commit when I think things are done, and I either have to put them in `MANIFEST` or `MANIFEST.SKIP`. I capture even incomplete work so I have it when I start again (and in a branch that's fine) or I accidentally delete the clone. I either clean up the branch I'm in or I don't get to release. It's how I keep myself honest.

However, this concrete issue highlights an abstract issue I've long thought about.

# The No Change solution

First, would setting git's `status.showUntrackedFile` for that repo work for you? I'm guessing that would affect other things you do, not just `release`, so that's probably out. That's the "no change" solution.

# Module shenanigans

Second, in the short term, you can have your own Module::Release::Git in the project. That initially sounds like it doesn't belong there, but if it's a mixin that's particular to how you want to do things in just that project, well, that's where it goes. With PERL5LIB, you can find the local copy first.

Of course, this means that your version and the CPAN version can diverge.

But, what you really want is a specialization of a module to do things differently. I wonder how that would work out with a subclass. With mixins I think it gets really messy because the inheritance is gone. You'd want to load some other module that re-implements the same things except for a few small changes. That's not particularly attractive.

# Env vars

Third, can we cheat temporarily with environment variables? Should we set some of those in `.releaserc` or from the session? I think this might be the best short term solution for you (if I patch Module::Release::Git). But, you changing the source of Module::Release::Git is 

    # .releaserc
    env_GIT_STATUS_OPTIONS = -uno

Or, 

    env  GIT_STATUS_OPTIONS=-uno release -t

Either of these would be easy to handle without big changes to Module::Release right away.

Or, read a per-project `.env`? That's a slightly bigger change but might be interesting anyway.


# Revamp config to allow per-mixin config

Fourth, perhaps there should be a way to add options of shell commands, or even other mixin things. This is a much bigger change and it might mess up some people who are using Module::Release (I am surprised that there are 11 forks)

I've been thinking some things would be easier if we switched over to TOML for `.releaserc`. We could then provide per-plugin configuration with sections:

     [Module::Release]
     ...

     [Module::Release::Git]
     status_options = -uno

**Comment by Tux** [comment]
I seriously like the revamp-config approach!

The `.env` variations might conflict with my workflow as I already use `.env` files for different stuff. Don't we all?

The No Change workflow forces me to change my git workflow. Doable, but of course not preferable.

I have less aversion to the Module Cheniagans workflow, as that would (for me) be easy to integrate in my already long list of patches and changes in cpanprefs/distroprefs, so installing updtes from CPAN will integrate my changes immediately (or FAIL and I have to alter my patch)

I would accept an ENV, but I don't think that this is a reliable way forward

Thanks for thinking along (as always)

**Comment by briandfoy** [comment]
Try the latest Module::Release::Git from the github repo. I added an `ignore_untracked` config value that will add `-uno` to the status command. It's a surgical change that should work for now.

**Comment by Tux** [comment]
Thank you, that'll work

**Comment by briandfoy** [comment]
Okay, I'll release that. If you have problems just open another ticket.
